# Generated by Django 2.2.13 on 2020-11-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201126_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalledeventa',
            old_name='activo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='activo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='activo',
            new_name='active',
        ),
    ]
