# Generated by Django 2.2.13 on 2020-11-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201126_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalledeventa',
            old_name='active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='active',
            new_name='activo',
        ),
    ]
