# Generated by Django 2.2.13 on 2020-11-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='api.Cliente'),
        ),
    ]
