from .user import UserSerializer, UserReadSerializer
from .s_detalle_venta import DetalleDeVentaCreateSerializer, DetalleDeVentaReadSerializer, DetalleDeVentaSerializer
from .s_factura import FacturaCreateSerializer, FacturaReadSerializer, FacturaSerializer,FacturaCreateCompraSerializer
from .s_producto import ProductoSerializer, ProductoReadSerializer, ProductoCreateSerializer, ReporteProductoSerializer
from .s_cliente import ClienteCrearSerializer, ClienteSerializer