from .user import UserSerializer, UserReadSerializer
from .s_detalle_venta import DetalleDeVentaCreateSerializer, DetalleDeVentaReadSerializer, DetalleDeVentaSerializer
from .s_factura import FacturaCreateSerializer, FacturaReadSerializer, FacturaSerializer
from .s_producto import ProductoSerializer, ProductoReadSerializer, ProductoCreateSerializer
